// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.23.0";

// src/lib/mcp/tools/about-whoop-whoop.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.23.0";
var about_whoop_whoop_default = defineTool({
  name: "about_whoop_whoop",
  title: "About WHOOP! WHOOP!",
  description: "Return an overview of WHOOP! WHOOP! \u2014 a competitive memory card game by Oleeha & Co: how it plays, player count, and links.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const text = [
      "WHOOP! WHOOP! is a competitive memory card game by Oleeha & Co.",
      "Players: 2\u20136. Recommended age: 7+.",
      "Cards vary by shape (circle, square, triangle, star), number (1\u20134), and color (red, blue, yellow).",
      "Each round the dice pick a matching rule (e.g. same color, same shape, different number). Peek at face-down cards to memorize them, then shout WHOOP! WHOOP! to claim a matching pair. Wrong claims freeze those cards and cost you your next flip.",
      "Play online: https://whoop-whoop.lovable.app/"
    ].join("\n");
    return { content: [{ type: "text", text }] };
  }
});

// src/lib/mcp/tools/list-matching-rules.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.23.0";
var list_matching_rules_default = defineTool2({
  name: "list_matching_rules",
  title: "List matching rules",
  description: "List the six matching rules used in WHOOP! WHOOP! Each roll of the dice selects one of these rules for the round.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const rules = [
      { id: "same-shape", label: "Same shape", description: "Both cards share the same shape." },
      { id: "same-number", label: "Same number", description: "Both cards show the same number of icons." },
      { id: "same-color", label: "Same color", description: "Both cards share the same color." },
      { id: "different-shape", label: "Different shape", description: "The two cards must have different shapes." },
      { id: "different-number", label: "Different number", description: "The two cards must show different numbers." },
      { id: "different-color", label: "Different color", description: "The two cards must be different colors." }
    ];
    const text = rules.map((r) => `\u2022 ${r.label} \u2014 ${r.description}`).join("\n");
    return {
      content: [{ type: "text", text }],
      structuredContent: { rules }
    };
  }
});

// src/lib/mcp/tools/list-cards.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.23.0";
var SHAPES = ["circle", "square", "tri", "star"];
var NUMBERS = [1, 2, 3, 4];
var COLORS = ["red", "blue", "yellow"];
var list_cards_default = defineTool3({
  name: "list_cards",
  title: "List cards",
  description: "List every card in the WHOOP! WHOOP! deck. Each card has a shape, number, and color; the deck is the full cartesian product (48 cards).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: () => {
    const cards = [];
    for (const shape of SHAPES) {
      for (const number of NUMBERS) {
        for (const color of COLORS) {
          cards.push({ id: `${shape}-${number}-${color}`, shape, number, color });
        }
      }
    }
    return {
      content: [{ type: "text", text: `${cards.length} cards in the deck (4 shapes \xD7 4 numbers \xD7 3 colors).` }],
      structuredContent: { count: cards.length, cards }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "whoop-whoop-mcp",
  title: "WHOOP! WHOOP! MCP",
  version: "0.1.0",
  instructions: "Public read-only tools for the WHOOP! WHOOP! memory card game by Oleeha & Co. Use `about_whoop_whoop` for an overview, `list_matching_rules` for the six round rules, and `list_cards` for the full card catalog.",
  tools: [about_whoop_whoop_default, list_matching_rules_default, list_cards_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.23.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
